# Generated by Django 4.2 on 2024-01-04 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='file',
            field=models.FileField(blank=True, upload_to='uploads/message/'),
        ),
        migrations.AlterField(
            model_name='message',
            name='flyer',
            field=models.ImageField(blank=True, upload_to='uploads/message_flyer/'),
        ),
    ]
