# Generated by Django 4.2 on 2024-01-04 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_message_file_alter_message_flyer'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='announcement',
            options={'ordering': ('-start_date',)},
        ),
        migrations.AlterField(
            model_name='announcement',
            name='end_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='flyer',
            field=models.ImageField(blank=True, upload_to='uploads/announcement_flyer/'),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='slug',
            field=models.SlugField(max_length=250, unique_for_date='start_date'),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='start_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='song',
            name='cover',
            field=models.ImageField(blank=True, upload_to='uploads/song_cover/'),
        ),
        migrations.AlterField(
            model_name='song',
            name='file',
            field=models.FileField(blank=True, upload_to='uploads/song/'),
        ),
        migrations.AlterField(
            model_name='song',
            name='lyrics',
            field=models.FileField(blank=True, upload_to='uploads/song_lyrics/'),
        ),
        migrations.AlterField(
            model_name='song',
            name='slug',
            field=models.SlugField(max_length=250),
        ),
    ]
