# Generated by Django 4.2 on 2024-01-04 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_announcement_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=50),
        ),
        migrations.AddField(
            model_name='song',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=50),
        ),
        migrations.AddField(
            model_name='testimony',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=50),
        ),
    ]
