# Generated by Django 4.2 on 2024-01-05 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newuser',
            name='role',
            field=models.CharField(choices=[('ICT', 'ICT'), ('MEDIA', 'MEDIA'), ('PUBLICATION', 'PUBLICATION'), ('MUSIC', 'MUSIC'), ('NIL', 'NIL')], max_length=50),
        ),
    ]
