# Generated by Django 4.2 on 2024-01-06 08:28

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_newuser_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='Music',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('user.newuser',),
            managers=[
                ('ict', django.db.models.manager.Manager()),
            ],
        ),
    ]
